name: CI/CD
on: push


jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14
        ports: [ "5432:5432" ]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Run rubocop
        run: |
          bin/rubocop
